import { Menu } from "@/components/Menu/";
import "../styles/globals.css";
import { Inter, JetBrains_Mono } from "next/font/google";
import { Header } from "@/components/header";
import { SocialLinksButton } from "@/components/Menu/SocialLinksButton";

const inter = Inter({ subsets: ["latin"] });
const jetBrainsMono = JetBrains_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio | Caio Freire",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <div className="h-screen flex justify-center items-center bg-app">
          <div
            className="bg-vscodeBg w-full max-w-[1480px] p-2 m-4 
            rounded-md
            aspect-video
            shadow-custom
            overflow-auto
            grid grid-rows-layout"
          >
            <Header />

            <div className="grid grid-cols-editor max-h-full">
              <Menu />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
